# Generated by Django 4.2.23 on 2025-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_order_address_order_phone_product_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('W', 'Waiting for Buyer Confirmation'), ('C', 'Completed'), ('X', 'Cancelled')], default='P', max_length=1),
        ),
    ]
