# Generated by Django 4.2.24 on 2025-10-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_alter_userprofile_role_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_type',
            field=models.CharField(choices=[('product_seller', 'Product Seller'), ('cafe_restaurant', 'Cafe and Restaurant'), ('service_provider', 'Service Provider')], default='product_seller', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
