# Generated by Django 4.2.24 on 2025-10-18 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_sellerprofile_business_type_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='availability_schedule',
            field=models.BooleanField(default=False, help_text='Whether scheduling is required'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_now',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_conditions',
            field=models.TextField(blank=True, help_text='Conditions for free delivery'),
        ),
        migrations.AddField(
            model_name='product',
            name='dietary_info',
            field=models.TextField(blank=True, help_text='Dietary restrictions, allergens, etc.'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of main ingredients'),
        ),
        migrations.AddField(
            model_name='product',
            name='preparation_time',
            field=models.CharField(blank=True, help_text='e.g., 15-20 minutes', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('custom', 'Custom Quote')], default='fixed', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='service_area',
            field=models.TextField(blank=True, help_text='Specific locations where service is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='service_duration',
            field=models.CharField(blank=True, help_text='e.g., 2 hours, 1 day', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(blank=True, default=dict, help_text='Available size options'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
