# Generated by Django 4.2.24 on 2025-10-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_alter_product_options_product_availability_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
